# Generated by Django 4.0.6 on 2022-08-01 12:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.UUID('4a3cd9fd-d23b-452c-a5d8-323b75388d67'), editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('cpf', models.CharField(max_length=14, verbose_name='Cpf')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.UUID('4a3cd9fd-d23b-452c-a5d8-323b75388d67'), editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('status', models.CharField(choices=[('order_created', 'Order created'), ('awayting_payment', 'Awayting payment'), ('order_processed', 'Order processed')], max_length=20, verbose_name='Status')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.customer', verbose_name='Customer Id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.UUID('4a3cd9fd-d23b-452c-a5d8-323b75388d67'), editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.UUID('4a3cd9fd-d23b-452c-a5d8-323b75388d67'), editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.order', verbose_name='Order Id')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product', verbose_name='Produto Id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='shop.product'),
        ),
    ]
