# Generated by Django 4.1 on 2022-08-04 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="cpf",
            field=models.CharField(max_length=14, unique=True, verbose_name="Cpf"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.customer",
                verbose_name="Customer Id",
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.order",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="products",
            field=models.JSONField(),
        ),
    ]
