# Generated by Django 4.1 on 2022-08-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_customer_cpf_alter_order_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="cpf",
            field=models.CharField(
                editable=False, max_length=14, unique=True, verbose_name="Cpf"
            ),
        ),
    ]
