# Generated by Django 4.1 on 2022-08-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_customer_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="cpf",
            field=models.CharField(max_length=14, unique=True, verbose_name="Cpf"),
        ),
    ]
