# Generated by Django 4.1 on 2022-08-10 23:21

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_rename_customer_id_order_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="products",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
