# Generated by Django 4.0.6 on 2022-08-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_order_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdetail",
            name="product_id",
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="products",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
